[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-Tkernel/link.ld"
]

[unstable]
build-std = ["core", "alloc"]
