[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.33.0", features = ["panic_handler", "alloc", "global_allocator", "unstable"] }
elf = { version = "0.7.4", default-features = false, features = ["nightly"] }
x86_64 = "0.15.2"
