[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "*", features = ["panic_handler", "alloc", "global_allocator"] }
elf = { version = "*", default-features = false }
